-- FIFA Tournament Manager - Production initialization SQL
-- Generated from packages/database/prisma/schema.prisma
-- Target: PostgreSQL / Supabase
--
-- Usage:
-- 1. Open Supabase SQL Editor.
-- 2. Paste this entire file.
-- 3. Run it once on an empty production database.
--
-- Notes:
-- - This SQL creates only schema objects, no seed data.
-- - Prisma cuid() values are generated by Prisma Client, so id columns do not use database defaults.
-- - Prisma @updatedAt is maintained by Prisma Client, so updatedAt columns do not use database triggers here.
-- - The _prisma_migrations table is intentionally not created here. The application does not need it at runtime.
--   If you later want Prisma migrate deploy to manage this database, use a proper Prisma baseline workflow.

BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'TournamentFormat') THEN
    CREATE TYPE "TournamentFormat" AS ENUM ('LEAGUE', 'KNOCKOUT', 'LEAGUE_KNOCKOUT');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'TournamentStatus') THEN
    CREATE TYPE "TournamentStatus" AS ENUM ('DRAFT', 'IN_PROGRESS', 'KNOCKOUT_STAGE', 'FINISHED');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ParticipantStatus') THEN
    CREATE TYPE "ParticipantStatus" AS ENUM ('PENDING', 'ACTIVE', 'REJECTED', 'ELIMINATED', 'CHAMPION');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'MatchStatus') THEN
    CREATE TYPE "MatchStatus" AS ENUM ('PENDING', 'FINISHED');
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'MatchPhase') THEN
    CREATE TYPE "MatchPhase" AS ENUM ('LEAGUE', 'ROUND_OF_16', 'QUARTER_FINAL', 'SEMI_FINAL', 'THIRD_PLACE', 'FINAL');
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS "users" (
  "id" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "email" TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "tournaments" (
  "id" TEXT NOT NULL,
  "ownerId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "slug" TEXT NOT NULL,
  "inviteCode" TEXT,
  "description" TEXT,
  "format" "TournamentFormat" NOT NULL,
  "status" "TournamentStatus" NOT NULL DEFAULT 'DRAFT',
  "isTwoLegged" BOOLEAN NOT NULL DEFAULT false,
  "qualifiedCount" INTEGER,
  "maxParticipants" INTEGER,
  "inviteEnabled" BOOLEAN NOT NULL DEFAULT true,
  "hasThirdPlaceMatch" BOOLEAN NOT NULL DEFAULT false,
  "championParticipantId" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "tournaments_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "participants" (
  "id" TEXT NOT NULL,
  "tournamentId" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "nickname" TEXT,
  "teamName" TEXT,
  "status" "ParticipantStatus" NOT NULL DEFAULT 'ACTIVE',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "participants_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "matches" (
  "id" TEXT NOT NULL,
  "tournamentId" TEXT NOT NULL,
  "phase" "MatchPhase" NOT NULL,
  "round" INTEGER,
  "homeParticipantId" TEXT,
  "awayParticipantId" TEXT,
  "homeScore" INTEGER,
  "awayScore" INTEGER,
  "homePenaltyScore" INTEGER,
  "awayPenaltyScore" INTEGER,
  "winnerParticipantId" TEXT,
  "status" "MatchStatus" NOT NULL DEFAULT 'PENDING',
  "matchOrder" INTEGER NOT NULL,
  "nextMatchId" TEXT,
  "nextMatchSlot" TEXT,
  "playedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "matches_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX IF NOT EXISTS "users_email_key" ON "users" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "tournaments_slug_key" ON "tournaments" ("slug");
CREATE UNIQUE INDEX IF NOT EXISTS "tournaments_inviteCode_key" ON "tournaments" ("inviteCode");

CREATE INDEX IF NOT EXISTS "tournaments_ownerId_idx" ON "tournaments" ("ownerId");
CREATE INDEX IF NOT EXISTS "tournaments_championParticipantId_idx" ON "tournaments" ("championParticipantId");
CREATE INDEX IF NOT EXISTS "participants_tournamentId_idx" ON "participants" ("tournamentId");
CREATE INDEX IF NOT EXISTS "matches_tournamentId_idx" ON "matches" ("tournamentId");
CREATE INDEX IF NOT EXISTS "matches_homeParticipantId_idx" ON "matches" ("homeParticipantId");
CREATE INDEX IF NOT EXISTS "matches_awayParticipantId_idx" ON "matches" ("awayParticipantId");
CREATE INDEX IF NOT EXISTS "matches_winnerParticipantId_idx" ON "matches" ("winnerParticipantId");
CREATE INDEX IF NOT EXISTS "matches_nextMatchId_idx" ON "matches" ("nextMatchId");

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'tournaments_ownerId_fkey'
  ) THEN
    ALTER TABLE "tournaments"
      ADD CONSTRAINT "tournaments_ownerId_fkey"
      FOREIGN KEY ("ownerId") REFERENCES "users"("id")
      ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'participants_tournamentId_fkey'
  ) THEN
    ALTER TABLE "participants"
      ADD CONSTRAINT "participants_tournamentId_fkey"
      FOREIGN KEY ("tournamentId") REFERENCES "tournaments"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matches_tournamentId_fkey'
  ) THEN
    ALTER TABLE "matches"
      ADD CONSTRAINT "matches_tournamentId_fkey"
      FOREIGN KEY ("tournamentId") REFERENCES "tournaments"("id")
      ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matches_homeParticipantId_fkey'
  ) THEN
    ALTER TABLE "matches"
      ADD CONSTRAINT "matches_homeParticipantId_fkey"
      FOREIGN KEY ("homeParticipantId") REFERENCES "participants"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matches_awayParticipantId_fkey'
  ) THEN
    ALTER TABLE "matches"
      ADD CONSTRAINT "matches_awayParticipantId_fkey"
      FOREIGN KEY ("awayParticipantId") REFERENCES "participants"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matches_winnerParticipantId_fkey'
  ) THEN
    ALTER TABLE "matches"
      ADD CONSTRAINT "matches_winnerParticipantId_fkey"
      FOREIGN KEY ("winnerParticipantId") REFERENCES "participants"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'matches_nextMatchId_fkey'
  ) THEN
    ALTER TABLE "matches"
      ADD CONSTRAINT "matches_nextMatchId_fkey"
      FOREIGN KEY ("nextMatchId") REFERENCES "matches"("id")
      ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END
$$;

COMMIT;
